SiteConfig:
  extensions:
    - InsiteApps\SocialMedia\SocialMediaExtension
    - InsiteApps\SocialMedia\SocialMediaSiteConfigExtension

Page:
  extensions:
    - InsiteApps\SocialMedia\SocialMediaPageExtension

PageController:
  extensions:
    - InsiteApps\SocialMedia\SocialMediaPageControllerExtension
